### ISSUE TITLE
cuando importo forensIT recibo warnings

### ISSUE THREAD

**Issue by tinamigo** [chernolabs/forensIT#3]
cuando importo forensIT recibo los siguientes warnings
```
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
2: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
3: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
4: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
5: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
6: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
```

Más adelante (en el readme) hay unos problemas con gráficos (que trato en otro issue). Pueden estar relacionados con estos warnings.

**Comment by MarsicoFL** [comment]
Gracias, no pude reproducir el error. Si tenés detalle de la versión bienvenido.

**Comment by tinamigo** [comment]
Lo corrí de nuevo para corroborar y no apareció el mensaje. Lo googleé y parece que es un mensaje de RStudio que tiene que ver con la ventanita de gráficos, no relacionado al código en sí. Así que todo en orden.
